# Generated by Django 4.1.6 on 2023-02-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
