# Generated by Django 4.1.6 on 2023-02-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_signup_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=20)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('Email', models.EmailField(max_length=20)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='signup',
            name='Photo',
        ),
    ]
