# Generated by Django 4.1.6 on 2023-02-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_image_remove_signup_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
