# Generated by Django 4.1.6 on 2023-02-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
